# Build Stage
FROM node:18-alpine as build
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Final Stage
FROM node:18-alpine
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY . .
RUN chmod -R 777 node_modules/
USER node
CMD ["yarn", "start"]
