# Debug Stage
FROM node:18-alpine as debug
WORKDIR /usr/src/app
EXPOSE 9222

# Build Stage
FROM node:18-alpine as build
WORKDIR /usr/src/app
RUN npm i -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Final Stage
FROM node:18-alpine
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY . .
RUN chmod -R 777 node_modules/
USER node
CMD ["pnpm", "run", "debug"]
