FROM node:18-slim

ENV VITE_API_ENV=dev

WORKDIR /usr/src/app
COPY --chown=node:node . /usr/src/app
RUN mkdir -p node_modules/.cache
RUN chmod -R 777 node_modules/.cache

RUN yarn install --frozen-lockfile
RUN yarn cache clean

USER node
CMD ["yarn", "start"]
