FROM apache/airflow:2.7.2-python3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

USER root
RUN apt-get update
RUN apt-get install nano -y

# Editable pip install for Domino from local folder
USER airflow
RUN mkdir -p domino/domino_py
COPY pyproject.toml domino/domino_py/
COPY src/domino domino/domino_py/src/domino
WORKDIR /opt/airflow/domino/domino_py
USER root
RUN chmod -R 777 .
USER airflow
RUN pip install -e .[airflow]

WORKDIR /opt/airflow