FROM apache/airflow:2.6.3-python3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
 
USER root
RUN apt-get update

USER airflow
RUN pip install --upgrade pip \
    pip install domino-py[airflow]