# # Airflow worker image to be used when running with docker-compose locally
# FROM apache/airflow:2.5.3-python3.9

# ENV PYTHONDONTWRITEBYTECODE=1
# ENV PYTHONUNBUFFERED=1

# USER root
# RUN apt-get update

# USER airflow
# RUN /usr/local/bin/python -m pip install --upgrade pip

# # Create folders to store source code
# RUN mkdir -p /home/domino/pieces_repository
# COPY ./pieces_repository_test /home/domino/pieces_repository

# # Create folder to store run data results
# RUN mkdir -p /home/run_data
# WORKDIR /home/run_data
# RUN chmod -R 777 .

# WORKDIR /home/domino
# RUN python3 -m venv venv \
#   source venv/bin/activate \
#   pip install domino-py

# TODO
# copy pieces repository source code to /domino/pieces_repository
# create compiled_metadata for all pieces

# provisory dockerfile
FROM apache/airflow:2.6.3-python3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

USER root
RUN apt-get update
RUN mkdir -p /home/shared_storage
WORKDIR /home/shared_storage
RUN chmod -R 777 .

WORKDIR /opt/airflow
# Editable pip install for Domino from local folder
USER airflow
RUN mkdir -p domino/domino_py
COPY setup.py domino/domino_py/
COPY requirements.txt domino/domino_py/
COPY requirements-airflow.txt domino/domino_py/
COPY README.md domino/domino_py/
COPY domino domino/domino_py/domino
# provisory repository used for testing only - remove it
COPY ./pieces_repository_test domino/pieces_repository 
COPY ./pieces_repository_test/.domino domino/pieces_repository/.domino
WORKDIR /opt/airflow/domino/domino_py
USER root
RUN chmod -R 777 .
USER airflow
RUN pip install -e .[airflow]

WORKDIR /opt/airflow/domino
RUN python3 -m venv venv --system-site-packages && source venv/bin/activate 
WORKDIR /opt/airflow/domino/domino_py
RUN pip install -e .


WORKDIR /opt/airflow


