FROM apache/airflow:2.5.3-python3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

USER root
RUN apt-get update
RUN apt-get install nano -y

# Editable pip install for Domino from local folder
USER airflow
RUN mkdir -p domino/domino_py
COPY setup.py domino/domino_py/
COPY requirements.txt domino/domino_py/
COPY requirements-airflow.txt domino/domino_py/
COPY README.md domino/domino_py/
COPY domino domino/domino_py/domino
WORKDIR /opt/airflow/domino/domino_py
USER root
RUN chmod -R 777 .
USER airflow
RUN pip install -e .[airflow]

WORKDIR /opt/airflow