# TODO - THIS IS NOT TESTED YET
# consider using this: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch
FROM nvidia/cuda:11.6.2-base-ubuntu20.04

# Installing Python with miniconda
RUN apt-get update && \
    apt-get install -y build-essential  && \
    apt-get install -y wget && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get -y update && \
    apt-get -y install python3 && \
    apt-get -y install python3-pip && \
    python3 -m pip install --upgrade pip

# Create folders to store source code
RUN mkdir -p /home/domino/pieces_repository

# Create folder to store run data results
RUN mkdir -p /home/run_data
WORKDIR /home/run_data
RUN chmod -R 777 .

# Create folder for sidecar pod mount to read xcom data
RUN mkdir -p /airflow/xcom/
RUN echo "{}" > /airflow/xcom/return.json
WORKDIR /airflow/xcom
RUN chmod -R 777 .

# Editable pip install for Domino from local folder
RUN mkdir -p /home/domino/domino_py
COPY setup.py /home/domino/domino_py/
COPY requirements.txt /home/domino/domino_py/
COPY requirements-airflow.txt /home/domino/domino_py/
COPY README.md /home/domino/domino_py/
COPY domino /home/domino/domino_py/domino
WORKDIR /home/domino/domino_py
RUN chmod -R 777 .
RUN pip install --no-cache -e .

WORKDIR /home