# Default values for installing Domino in a K8s cluster

github_access_token_pieces: default-substitute-this-for-your-own-token
github_access_token_workflows: default-substitute-this-for-your-own-token

ingress:
  hostName: localhost

# Frontend service
frontend:
  enabled: true
  image: ghcr.io/tauffer-consulting/domino-frontend
  tag: latest
  apiUrl: http://localhost/api

# REST service
rest:
  enabled: true
  image: ghcr.io/tauffer-consulting/domino-rest
  tag: latest
  deployMode: local-k8s # TODO change to prod
  # Github workflows repository name - Same one used in airflow gitSync ssh
  workflowsRepository: ~
  createDefaultUser: true

# Change this if using external Database
database:
  enabled: true
  image: postgres:13
  name: postgres
  user: postgres
  password: postgres
  port: "5432"
