"""Add_is_composite_column_to_piece_table

Revision ID: 2b760e779b0e
Revises: 758034ba1a89
Create Date: 2023-11-09 02:29:27.898527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b760e779b0e'
down_revision = '758034ba1a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('is_composite', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'is_composite')
    # ### end Alembic commands ###
