"""empty message

Revision ID: 465e157aef25
Revises: 483a5fbb2768
Create Date: 2023-05-13 17:50:39.937024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465e157aef25'
down_revision = '483a5fbb2768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'source_url')
    # ### end Alembic commands ###
