"""empty message

Revision ID: 483a5fbb2768
Revises: 851c49af162b
Create Date: 2023-05-09 09:39:09.365831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483a5fbb2768'
down_revision = '851c49af162b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_repository', sa.Column('label', sa.String(length=50)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece_repository', 'label')
    # ### end Alembic commands ###
