"""empty message

Revision ID: 758034ba1a89
Revises: c25e53090da7
Create Date: 2023-10-30 13:58:20.061180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '758034ba1a89'
down_revision = 'c25e53090da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('schedule', sa.Enum('none', 'once', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'Config', name='workflowscheduleinterval'), nullable=True))
    op.drop_column('workflow', 'schedule_interval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('schedule_interval', postgresql.ENUM('none', 'once', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'Config', name='workflowscheduleinterval'), autoincrement=False, nullable=True))
    op.drop_column('workflow', 'schedule')
    # ### end Alembic commands ###
