"""empty message

Revision ID: 93da7356c3d7
Revises: f7214a10a4df
Create Date: 2023-11-29 07:55:27.576939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93da7356c3d7'
down_revision = 'f7214a10a4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('piece', sa.Column('container_resources', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'container_resources')
    op.drop_column('piece', 'tags')
    # ### end Alembic commands ###
