"""Added url column to PieceRepository table

Revision ID: c25e53090da7
Revises: e5d6ca5e4865
Create Date: 2023-09-02 14:38:49.139678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25e53090da7'
down_revision = 'e5d6ca5e4865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece_repository', sa.Column('url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece_repository', 'url')
    # ### end Alembic commands ###
