"""add_assembled_piece_table

Revision ID: e1dd5824070b
Revises: 758034ba1a89
Create Date: 2023-11-02 01:55:14.003643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1dd5824070b'
down_revision = '758034ba1a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembled_piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('dependency', sa.JSON(), nullable=True),
    sa.Column('input_schema', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_schema', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('secrets_schema', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('style', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assembled_piece')
    # ### end Alembic commands ###
