"""empty message

Revision ID: eddc26bcfcfa
Revises: 758034ba1a89
Create Date: 2023-11-09 08:17:01.340094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddc26bcfcfa'
down_revision = '758034ba1a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('forage_schema', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'forage_schema')
    # ### end Alembic commands ###
