"""empty message

Revision ID: eedbcfa88cd9
Revises: 465e157aef25
Create Date: 2023-05-15 09:57:38.963917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'eedbcfa88cd9'
down_revision = '465e157aef25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    status = postgresql.ENUM('pending', 'accepted', 'rejected', name='userworkspacestatus')
    status.create(op.get_bind())
    op.add_column('user_workspace_associative', sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='userworkspacestatus'), server_default='pending', nullable=True))
    op.execute("UPDATE user_workspace_associative SET status = 'accepted'")
    op.alter_column('user_workspace_associative', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_workspace_associative', 'status')
    # ### end Alembic commands ###
