"""fix_assembled_piece_table

Revision ID: f786dddf571f
Revises: e1dd5824070b
Create Date: 2023-11-02 02:32:33.232267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f786dddf571f'
down_revision = 'e1dd5824070b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assembled_piece', 'workflow_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'assembled_piece', ['workflow_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assembled_piece', type_='unique')
    op.alter_column('assembled_piece', 'workflow_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
